basePath: /
definitions:
  presenter.Dandelion:
    properties:
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is Uta API for PLANE_WEB.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Uta API
  version: "1.0"
paths:
  /dandelions:
    get:
      consumes:
      - application/json
      description: タンポポの一覧を取得する。
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/presenter.Dandelion'
            type: array
      summary: タンポポ一覧取得
      tags:
      - Dandelions
swagger: "2.0"
