import React from "react";
import { Heading, Text, VStack, Flex, Image, Center } from "@chakra-ui/react";
import { useNavigate } from "react-router-dom";

const Confirmation: React.FC = () => {
  const navigate = useNavigate();
  return (
    <Flex minH="100px" display="flex" justify="center" align="center" pb="30px">
      <VStack>
        <Heading
          fontSize="18px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          1. 写真
        </Heading>
        <Center>
          <Image
            src="https://d2v9opmik2a3uk.cloudfront.net/uploads/2019/05/15161942/c2e9ddc2562db5960c1b449c4eec5351_1557937181.jpg"
            boxSize="200px"
            objectFit="cover"
            pb="40px"
          />
        </Center>
        <Heading
          fontSize="18px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          2. 特徴
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          pb="30px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          あれこれそれあれこれそれあれこれそれあれこれそれあれこれそれあれこれそれあれこれそれあれこれそれ
        </Text>
        <Heading
          fontSize="18px"
          m="5px"
          pt="20px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          3. 咲いていた場所
        </Heading>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          3-1. 住所
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          xx県xx市xxxxx
        </Text>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          3-2. 目印
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          oo公園
        </Text>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          3-3. 緯度・経度
        </Heading>
        <Heading
          fontSize="12px"
          m="5px"
          pt="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          北緯
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          23.1度
        </Text>
        <Heading
          fontSize="12px"
          m="5px"
          pt="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          東経
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          23.1度
        </Text>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          3-4. どんな場所
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          池の土手
        </Text>
        <Heading
          fontSize="18px"
          m="5px"
          pt="20px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          4. 調査者の情報
        </Heading>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          4-1. 名前
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          専修太郎
        </Text>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          4-2. 住所
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          xx県xx市xxxxx
        </Text>
        <Heading
          fontSize="14px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          4-3. 電話番号
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          xxx-xxxx-xxxx
        </Text>
        <Heading
          fontSize="18px"
          m="5px"
          py="10px"
          w="full"
          textAlign="left"
          color="green.800"
        >
          5. 感想
        </Heading>
        <Text
          fontSize="14px"
          mx="15px"
          mb="20px"
          w="230px"
          textAlign="left"
          color="green.800"
        >
          あれこれそれあれこれそれあれこれそれあれこれそれあれこれそれ
        </Text>
      </VStack>
    </Flex>
  );
};

export default Confirmation;
