version: '3'

services:
  db:
    image: mysql:8.0
    container_name: DandeDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dandes
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - 3306
    volumes:
      - "./data/mysql:/var/lib/mysql"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -pパスワード
    ports:
      - "3306:3306"

  doc:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc/api/swagger.yaml:/usr/share/nginx/html/api.yaml
    environment:
      API_URL: api.yaml
    ports:
      - '8081:8080'
